// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVV6ShGF2uBFaxdHdkyqbBjQUngHPRiM',
    appId: '1:106627546775:android:5609f0c7e50a91e12773d2',
    messagingSenderId: '106627546775',
    projectId: 'appislam-flutter',
    storageBucket: 'appislam-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM5sS3ZwJPniw3yNeGrJy4me4s1SXYZKQ',
    appId: '1:106627546775:ios:1cc246a20c4a56b32773d2',
    messagingSenderId: '106627546775',
    projectId: 'appislam-flutter',
    storageBucket: 'appislam-flutter.firebasestorage.app',
    androidClientId: '106627546775-blt9sm92rqp2i5edlbm8nfvd0o057gb6.apps.googleusercontent.com',
    iosClientId: '106627546775-8n2757sii6d84f2ur1pevkb8taskrnmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.appislam',
  );

}